language: python
sudo: false
dist: trusty
matrix:
  include:
    - python: 2.7
      env: PYENV=py27
    - python: 3.6
      env: PYENV=py36
addons:
  apt:
    packages:
      - build-essential
      - autoconf
      - automake
      - libtool
      - libreadline6-dev
      - libncurses5-dev
      - libgsl0-dev
      - python-dev
      - python3-dev
      - python-numpy
      - python-scipy
      - python3-numpy
      - python3-scipy
      - openmpi-bin
      - libopenmpi-dev
      - inkscape
      - libhdf5-serial-dev
      - libyaml-dev
install:
  - linux_install/nest.sh 2.12.0
  - linux_install/neuron.sh 7.5
  - pip install git+git://github.com/tclose/nineml-python.git@pype9_port
  - pip install git+git://github.com/tclose/nineml-catalog.git@python3
  - pip install git+git://github.com/tclose/Diophantine.git@master
  - wget https://github.com/NeuralEnsemble/PyNN/archive/0.9.1.tar.gz
  - tar xzf 0.9.1.tar.gz
  - mv PyNN-0.9.1 pyNN-$PYENV
  - pip install ./pyNN-$PYENV
  - pip install -r requirements.txt
  - pip install coveralls
  - pushd pype9/simulate/neuron/cells/code_gen/libninemlnrn
  - CC=mpicc ./manual_compile.sh
  - popd
script:
  - nosetests test --with-coverage --cover-package=pype9
after_success:
  - coveralls
