language: python
sudo: false
dist: trusty
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.6
addons:
  apt:
    packages:
      - build-essential
      - autoconf
      - automake
      - libtool
      - libreadline6-dev
      - libncurses5-dev
      - libgsl0-dev
      - python-dev
      - python3-dev
      - python-numpy
      - python-scipy
      - python3-numpy
      - python3-scipy
      - openmpi-bin
      - libopenmpi-dev
      - inkscape
      - libhdf5-serial-dev
      - libyaml-dev
install:
  - pip install --upgrade cmake  # For NEST installation
  - cmake --version
  - install/nest.sh 2.14.0
  - install/neuron.sh tag-9fc719735a2d0a9446f59065534d5326a6bd179d
  - pip install git+git://github.com/tclose/nineml-python.git@pype9_port
  - pip install git+git://github.com/tclose/nineml-catalog.git@python3
  - pip install git+git://github.com/tclose/Diophantine.git@master
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests test/unittests --with-coverage --cover-package=pype9
after_success:
  - coveralls
