language: python
python:
  - "2.7"
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - build-essential
      - autoconf
      - automake
      - libtool
      - libreadline6-dev
      - libncurses5-dev
      - libgsl0-dev
      - python-all-dev
      - python-numpy
      - python-scipy
      - openmpi-bin
      - libopenmpi-dev
install:
  - source prereq/install_nest.sh
  - source prereq/install_neuron.sh
  - wget https://github.com/sympy/sympy/archive/master.zip && unzip master.zip && pip install ./sympy-master
  - pip install -r requirements.txt
  - wget https://github.com/tclose/lib9ML/archive/develop.zip && unzip develop.zip && pip install ./lib9ML-develop
  - wget https://github.com/tclose/NineMLCatalog/archive/merging_with_master.zip && unzip merging_with_master.zip && pip install ./NineMLCatalog-merging_with_master  
  - pip install coveralls
  - pip install .
  - export WD=`pwd`
  - cd ./pype9/neuron/cells/code_gen/libninemlnrn
  - make
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/pype9/neuron/cells/code_gen/libninemlnrn:$LD_LIBRARY_PATH
  - cd $WD
script:
  - nosetests test/test_*.py --with-coverage --cover-package=pype9
after_success:
  coveralls
