language: python
sudo: True
dist: trusty
matrix:
  include:
    - python: 2.7
    - python: 3.6
addons:
  apt:
    packages:
      - build-essential
      - autoconf
      - automake
      - libtool
      - libreadline6-dev
      - libncurses5-dev
      - libgsl0-dev
      - python-dev
      - python3-dev
      - python-numpy
      - python-scipy
      - python3-numpy
      - python3-scipy
      - openmpi-bin
      - libopenmpi-dev
      - inkscape
      - libhdf5-serial-dev
      - libyaml-dev
install:
  - install/nest.sh 2.14.0
  - install/neuron.sh tag-1665alpha
  - pip install -e .[plot]
  - pip install nose coveralls
script:
  - nosetests test/unittests --with-coverage --cover-package=pype9
after_success:
  - coveralls
