language: python
sudo: false
dist: trusty
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.6
addons:
  apt:
    packages:
      - build-essential
      - autoconf
      - automake
      - libtool
      - libreadline6-dev
      - libncurses5-dev
      - libgsl0-dev
      - python-dev
      - python3-dev
      - python-numpy
      - python-scipy
      - python3-numpy
      - python3-scipy
      - openmpi-bin
      - libopenmpi-dev
      - inkscape
      - libhdf5-serial-dev
install:
  - source ci/install_nest.sh 2.12.0 purge
  - source ci/install_neuron.sh 7.5 purge
  - pip install git+git://github.com/tclose/nineml-python.git@pype9_port
  - pip install git+git://github.com/tclose/nineml-catalog.git@python3
  - pip install git+git://github.com/tclose/Diophantine.git@master
  - pip install -r requirements.txt
  - pip install coveralls
  - pushd pype9/simulate/neuron/cells/code_gen/libninemlnrn
  - CC=mpicc ./manual_compile.sh
  - popd
script:
  - nosetests test --with-coverage --cover-package=pype9
after_success:
  - coveralls
cache:
  directories:
    - $NEST_SRC_DIR
    - $NEST_BUILD_DIR
    - $NEURON_SRC_DIR
    - $NEURON_BUILD_DIR
    - $HOME/.cache/pip
