language: python
python:
  - "2.7"
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - build-essential
      - autoconf
      - automake
      - libtool
      - libreadline6-dev
      - libncurses5-dev
      - libgsl0-dev
      - python-all-dev
      - python-numpy
      - python-scipy
      - openmpi-bin
      - libopenmpi-dev
      - inkscape
install:
  - pip install cython
  - source prereq/install_nest.sh
  - source prereq/install_neuron.sh
  - pip install -r requirements.txt
  - pip install https://github.com/sympy/sympy/archive/master.zip  
  - pip install https://github.com/tclose/lib9ML/archive/develop.zip
  - pip install https://github.com/tclose/NineMLCatalog/archive/merging_with_master.zip  
  - pip install coveralls
  - pip install -v .
script:
  - pushd test
  - nosetests . --exe --with-coverage --cover-package=pype9
  - popd
after_success:
  - coveralls
cache:
  directories:
    - $HOME/nest-2.10.0
    - $HOME/nrn-7.4
    - $HOME/build/nest-2.10.0
    - $HOME/build/nrn-7.4
    - $HOME/.cache/pip
