language: python
python:
  - "2.7"
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - build-essential
      - autoconf
      - automake
      - libtool
      - libreadline6-dev
      - libncurses5-dev
      - libgsl0-dev
      - python-all-dev
      - python-numpy
      - python-scipy
      - openmpi-bin
      - libopenmpi-dev
      - inkscape
      - libhdf5-serial-dev
install:
  - pip install cython
  - source ci/install_neuron.sh
  - source ci/install_nest.sh
  - pip install git+git://github.com/tclose/nineml-python.git@0.2
  - pip install -e .
  - pip install coveralls
  - pushd pype9/simulate/neuron/cells/code_gen/libninemlnrn
  - CC=mpicc ./manual_compile.sh
  - popd
script:
  - nosetests test --with-coverage --cover-package=pype9
after_success:
  - coveralls
cache:
  directories:
    - $HOME/nest-2.10.0
    - $HOME/nrn-7.4
    - $HOME/build/nest-2.10.0
    - $HOME/build/nrn-7.4
    - $HOME/.cache/pip
